# Generated by Django 2.2 on 2019-04-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summery',
            field=models.TextField(),
        ),
    ]
